version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: blog_postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'blog'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
